import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dm_Sans = DM_Sans({
  subsets: ["latin"]
})
export const metadata: Metadata = {
  title: "OpenCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dm_Sans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
